FROM nginx

COPY conway.html /usr/share/nginx/html/conway.html
COPY conway.js /usr/share/nginx/html/conway.js
COPY conway.png /usr/share/nginx/html/conway.png
COPY conway.wasm /usr/share/nginx/html/conway.wasm
COPY conway.pck /usr/share/nginx/html/conway.pck
